### ISSUE TITLE
9V battery PCB

### ISSUE THREAD

**Issue by bobthechemist** [electronut/attiny85-mma7660#1]
Can you provide some details about the PCB on the 9V battery displayed in your picture?  I've seen it in a couple of your other designs and assume its a 5V/3.3V regulator but would like to know if its your own design or if you've obtained it from another source.

**Comment by electronut** [comment]
Hi @bobthechemist 

It's called snapVCC - a product that I designed, and it's available for purchase from our Tindie store:

https://www.tindie.com/stores/ElectronutLabs/

Regards

Mahesh Venkitachalam
Founder, Electronut Labs
electronut.in
